
name: Postman API Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run API Tests with Newman
         run: |
          newman run "Restful Booker.postman_collection.json" \
            --environment "Testing.postman_environment.json" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman/report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
         name: API-Test-Report
          path: newman/report.html
